name = "winter-credit-2442"
main = "./supabase_ping/supabase_ping.mjs"
type = "javascript" # Usaremos el archivo JS compilado
workers_dev = true
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]
[triggers]
crons = ["0 9 * * 1,4"] # Cron job: Lunes y jueves a las 9:00 AM UTC